name: "Hello World"
description: "Greet someone and record the time"
inputs:
    token:
        required: true
    keystore-base64:
        required: true
    keystore-filename:
        required: true
    keystore-path:
        default: ./android
    platform:
        default: android
    version-name:
        default: alpha
outputs:
    time: # id of output
        description: "The time we greeted you"
runs:
    using: "node16"
    main: "action/index.js"
