name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    required: true
  version-name:
    default: alpha
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'action/index.js'
