name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  firebase-id: # id of input
    description: 'Who to greet'
    required: true
    default: 'top'
  token-pat:
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'action/index.js'
